### ISSUE TITLE
Polish description on settings site.

### ISSUE THREAD

**Issue by adamlagoda** [richtr/Opera-Translate#2]
![translation-polish](https://cloud.githubusercontent.com/assets/9074283/4557114/2f7618d8-4ed0-11e4-80f1-ae77b8fcf781.jpg)

Here I attached a screenshot with a marked mistakes which were made during translation. They're not cardinal but may irritate someone who's concerned about grammar. 
I don't know, how to correct those mistakes, so below I put corrections for every point:
1.Automatycznie zapytaj o przetłumaczenie strony internetowej.
2. Wybranie "Nie" dodaje do przeglądarki przycisk, dla stron możliwych do przetłumaczenia.
3. Automatyczne tłumaczenie stron internetowych w momencie ich odwiedzenia.
4. Zmień ustawienia dla poszczególnych języków.
I suppose polish viewers wil appreciate those changes.
Thanks a lot :)

**Comment by firuz-7** [comment]
richtr 
thanks for expansion
when there is an update https://addons.opera.com/en/extensions/details/translate-4/ this extension, please do so as he was in chromium, a small window with the right to open and asked to be transferred or not
I hope soon will be an update

спасибо за расширения
когда будет обновления https://addons.opera.com/en/extensions/details/translate-4/  этого расширения, сделайте пожалуйста чтобы он был как в хроме, маленькое окошка с права открывалась и просила перевести или нет
надеюсь скоро будет обновления
